### ISSUE TITLE
Failed to split the NUT_DATA.txt file.

### ISSUE THREAD

**Issue by vegantraveler** [csmcprojects/USDASR28-ASCII-to-MySQL-PHP-Script#1]
Hi, I'm running this PHP in a local machine to populate a new database with the SR28.

I get this "Failed to split the NUT_DATA.txt file." message. Would it be because it is on a local environment and should run it on a live server?

I'm running it on MAMP 4.4.1 and tried with both PHP 7.1.12 and 7.2.1

**Comment by samfieldscc** [comment]
That error message shows when the script was not able to open the NUT_DATA.txt file. And should not be related to the fact that you are running it in a local environment and not a live server.

I think the problem is with opening the file, because if your script is getting an error only at that point then it means it already downloaded and unzipped the SR28 files successfully. But I can't tell you more without more information.

My advice is that you make sure that the file does exist in the path the script is looking at (that will be the folder defined by the DOWNLOAD_SR28_PATH constant). So make sure you defined a path where the script will have permission to download and **OPEN the file** (write and read permissions).

To help debug you can set the following settings that are defined in lines 49 and 50:

`
ini_set('display_errors',"1");
error_reporting(E_ALL);
`

And please make sure you have the latest version of the script.
